POST http://localhost:4000/app/appointment
Content-Type: application/json

{
  "fullName": "Value AnotherValue",
  "email": "email@email.com",
  "operation": "Unbritish his teeth",
  "cost": 4574,
  "date": "10/14/2022"
}