POST http://localhost:4000/app/appointments
Content-Type: application/json

{
  "fullName": "Name",
  "email": "new@email.com",
  "operation": "Unbritish his teeth",
  "cost": 100000,
  "date": "11/14/2022"
}